services:
  app:
    image: node:20-alpine
    container_name: nextjs_container
    working_dir: /app
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm config set strict-ssl false && npm i && npm run dev"
    depends_on:
      - database
    environment:
      POSTGRES_USER: agende_cabelo_root
      POSTGRES_PASSWORD: ygy2352s3h
      POSTGRES_DB: agende_cabelo
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      AUTH_SECRET: 9vol8epcgj%ygy2352s3h!8epcg#.AgendeCabelo
  database:
    image: postgres:latest
    container_name: postgre_container
    restart: always
    environment:
      POSTGRES_USER: agende_cabelo_root
      POSTGRES_PASSWORD: ygy2352s3h
      POSTGRES_DB: agende_cabelo
    ports:
      - "5433:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d